language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install -e src
  - pip install coveralls sphinx-bootstrap-theme
script: 
  - coverage run --rcfile=config/coverage.conf setup.py test
  - make html
after_script:
  - coveralls
