language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install --upgrade pip
  - pip install -e src
# mdtraj
  - pip install --no-use-wheel cython
  - pip install --no-use-wheel mdtraj
# MDAnalysis
  - pip install --no-use-wheel MDAnalysis
# Coverage testing and documentation
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx-bootstrap-theme
cache:
  directories:
    - $HOME/.cache/pip
script:
  - cd src
  - coverage run --rcfile=../config/coverage.conf setup.py test
  - cd ..
  - make html
after_script:
  - cd src
  - coveralls
