language: python
python:
  - "2.7"
  - "2.6"
install:
  - pip install --upgrade pip
  - pip install -e src
  - pip install -q -r config/requirements.txt
script:
  - cd src
  - coverage run --rcfile=../config/coverage.conf setup.py test
  - cd ..
  - make html
after_script:
  - cd src
  - coveralls
